# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sql_agent_pb2 as sql__agent__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sql_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SqlAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSQL = channel.unary_unary(
                '/sql_agent.v1.SqlAgent/GenerateSQL',
                request_serializer=sql__agent__pb2.GenerateSQLRequest.SerializeToString,
                response_deserializer=sql__agent__pb2.GenerateSQLResponse.FromString,
                _registered_method=True)
        self.ExecuteSQL = channel.unary_unary(
                '/sql_agent.v1.SqlAgent/ExecuteSQL',
                request_serializer=sql__agent__pb2.ExecuteSQLRequest.SerializeToString,
                response_deserializer=sql__agent__pb2.ExecuteSQLResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sql_agent.v1.SqlAgent/HealthCheck',
                request_serializer=sql__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=sql__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class SqlAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateSQL(self, request, context):
        """Produce a structured query plan for a natural-language question.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteSQL(self, request, context):
        """Execute a natural-language query end-to-end and return plan + data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Liveness / readiness probe for Kubernetes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqlAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSQL,
                    request_deserializer=sql__agent__pb2.GenerateSQLRequest.FromString,
                    response_serializer=sql__agent__pb2.GenerateSQLResponse.SerializeToString,
            ),
            'ExecuteSQL': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteSQL,
                    request_deserializer=sql__agent__pb2.ExecuteSQLRequest.FromString,
                    response_serializer=sql__agent__pb2.ExecuteSQLResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sql__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=sql__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sql_agent.v1.SqlAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sql_agent.v1.SqlAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SqlAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sql_agent.v1.SqlAgent/GenerateSQL',
            sql__agent__pb2.GenerateSQLRequest.SerializeToString,
            sql__agent__pb2.GenerateSQLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sql_agent.v1.SqlAgent/ExecuteSQL',
            sql__agent__pb2.ExecuteSQLRequest.SerializeToString,
            sql__agent__pb2.ExecuteSQLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sql_agent.v1.SqlAgent/HealthCheck',
            sql__agent__pb2.HealthCheckRequest.SerializeToString,
            sql__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
