# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sql_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sql_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsql_agent.proto\x12\x0csql_agent.v1\"1\n\x10\x43hatMessageProto\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x87\x01\n\x12GenerateSQLRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x16\n\x0ememory_summary\x18\x03 \x01(\t\x12\x36\n\x0eprior_messages\x18\x04 \x03(\x0b\x32\x1e.sql_agent.v1.ChatMessageProto\"\x91\x01\n\x13GenerateSQLResponse\x12\x11\n\ttool_used\x18\x01 \x01(\t\x12\x17\n\x0fparameters_json\x18\x02 \x01(\t\x12\x17\n\x0fparam_reasoning\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x12\n\nlatency_ms\x18\x05 \x01(\x01\x12\x12\n\nsession_id\x18\x06 \x01(\t\"\x86\x01\n\x11\x45xecuteSQLRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x16\n\x0ememory_summary\x18\x03 \x01(\t\x12\x36\n\x0eprior_messages\x18\x04 \x03(\x0b\x32\x1e.sql_agent.v1.ChatMessageProto\"\xf4\x01\n\x12\x45xecuteSQLResponse\x12\x11\n\ttool_used\x18\x01 \x01(\t\x12\x17\n\x0fparameters_json\x18\x02 \x01(\t\x12\x17\n\x0fparam_reasoning\x18\x03 \x01(\t\x12\x11\n\trow_count\x18\x04 \x01(\x05\x12\x11\n\trows_json\x18\x05 \x01(\t\x12\x10\n\x08insights\x18\x06 \x01(\t\x12\x19\n\x11visualization_b64\x18\x07 \x01(\t\x12\r\n\x05\x65rror\x18\x08 \x01(\t\x12\x0f\n\x07success\x18\t \x01(\x08\x12\x12\n\nlatency_ms\x18\n \x01(\x01\x12\x12\n\nsession_id\x18\x0b \x01(\t\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x83\x02\n\x08SqlAgent\x12R\n\x0bGenerateSQL\x12 .sql_agent.v1.GenerateSQLRequest\x1a!.sql_agent.v1.GenerateSQLResponse\x12O\n\nExecuteSQL\x12\x1f.sql_agent.v1.ExecuteSQLRequest\x1a .sql_agent.v1.ExecuteSQLResponse\x12R\n\x0bHealthCheck\x12 .sql_agent.v1.HealthCheckRequest\x1a!.sql_agent.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sql_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGEPROTO']._serialized_start=33
  _globals['_CHATMESSAGEPROTO']._serialized_end=82
  _globals['_GENERATESQLREQUEST']._serialized_start=85
  _globals['_GENERATESQLREQUEST']._serialized_end=220
  _globals['_GENERATESQLRESPONSE']._serialized_start=223
  _globals['_GENERATESQLRESPONSE']._serialized_end=368
  _globals['_EXECUTESQLREQUEST']._serialized_start=371
  _globals['_EXECUTESQLREQUEST']._serialized_end=505
  _globals['_EXECUTESQLRESPONSE']._serialized_start=508
  _globals['_EXECUTESQLRESPONSE']._serialized_end=752
  _globals['_HEALTHCHECKREQUEST']._serialized_start=754
  _globals['_HEALTHCHECKREQUEST']._serialized_end=774
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=776
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=830
  _globals['_SQLAGENT']._serialized_start=833
  _globals['_SQLAGENT']._serialized_end=1092
# @@protoc_insertion_point(module_scope)
